### PR TITLE
128 update report content

### PR DESCRIPTION
**Pull request by AndrzejKaj**

### CODE REVIEW

**Review by azywot — COMMENTED** [review]
I am wondering whether it is possible to loose the interactivity in the reports, as having  the settings and the files, one's just able to reproduce it and interact in the app, plus it reduces the size significantly.
Have you checked maybe anything similar to this [this](https://thepythoncode.com/article/convert-html-to-pdf-in-python) one?

**Comment by AndrzejKaj** [comment]
> I am wondering whether it is possible to loose the interactivity in the reports, as having the settings and the files, one's just able to reproduce it and interact in the app, plus it reduces the size significantly. Have you checked maybe anything similar to this [this](https://thepythoncode.com/article/convert-html-to-pdf-in-python) one?

Yes, wkhtmltopdf tool is tool which is tried to add to our app, but like I said wkhtmltopdf need to be added to PATH.

**Comment by azywot** [comment]
> > I am wondering whether it is possible to loose the interactivity in the reports, as having the settings and the files, one's just able to reproduce it and interact in the app, plus it reduces the size significantly. Have you checked maybe anything similar to this [this](https://thepythoncode.com/article/convert-html-to-pdf-in-python) one?
> 
> Yes, wkhtmltopdf is tool which I tried to add to our app, but like I said wkhtmltopdf need to be added to PATH.

Ahh okay, if that's the case and there's no direct workaround, then it's fine 👍

**Review by Tremirre — APPROVED** [review]
LGTM 👌

**Review by azywot — APPROVED** [review]

**Pull request merged**
