### PR TITLE
closes 140 configuration for hit determination

### PR DESCRIPTION
**Pull request by Tremirre**
Extended configuration with top bounds; now the activity determination uses the configured values instead of predefined constants - albeit the default values equal the ones from KNIME workflow.
This allows the user to influence the rules on how to classify activity of the compounds:
image

Proof of work - classification of **EOS100028**:
---

default settings - classified as ACTIVE as IC50 <= 10 & IC50 > 0 AND TOP > 30:
image

classification with set concentration upper bound for IC50 to 0.5 - classified as INACTIVE:
image

As previously discussed - constants for `ALL_CONC_ACTIVE` and `ALL_CONC_INACTIVE` features remain as such.
Note - as the determination is calculated whenever the file is uploaded, after changing the configuration that file needs to be re-uploaded to reflect new configuration.

### CODE REVIEW

**Review by azywot — APPROVED** [review]
LGTM GJ 👍👍

Maybe one styling suggestion - how about switching the rows order here:
obraz
would be more intuitive imo

**Review by AndrzejKaj — APPROVED** [review]

**Review by zuzg — APPROVED** [review]

**Comment by Tremirre** [comment]
> LGTM GJ 👍👍
> 
> Maybe one styling suggestion - how about switching the rows order here: obraz would be more intuitive imo

You mean so that the `Lower Bound` is above `Upper bound`?

**Comment by azywot** [comment]
> > LGTM GJ 👍👍
> > Maybe one styling suggestion - how about switching the rows order here: obraz would be more intuitive imo
> 
> You mean so that the `Lower Bound` is above `Upper bound`?

Yeah, I'd start with lower and then upper bound while setting, though if the placing was meant to resemble bottom/up itself,  then it's okay too.

**Comment by Tremirre** [comment]
> > > LGTM GJ 👍👍
> > > Maybe one styling suggestion - how about switching the rows order here: obraz would be more intuitive imo
> > 
> > 
> > You mean so that the `Lower Bound` is above `Upper bound`?
> 
> Yeah, I'd start with lower and then upper bound while setting, though if the placing was meant to resemble bottom/up itself, then it's okay too.

yeah, that's what I had in mind, maybe the rest of the team might give their opinion on what would look best? @zuzg  @AndrzejKaj

**Comment by zuzg** [comment]
Well for me it actually makes sense that the `TOP` is on the top :D

**Comment by Tremirre** [comment]
okay in that case I'll merge this PR, we can always ask the client/Dabrze about this

**Pull request merged**
