### PR TITLE
closes 96 update stage 2 layout

### PR DESCRIPTION
**Pull request by Tremirre**
I adjusted the laout of stage 2, should be better now.

I increased the number of displayed plates to 12 and disabled the controls, but as of yet I hadn't found a way to disable zooming/panning or grids on subplots:

```python
    fig.update_layout(
        {
            "xaxis": {"fixedrange": True, "showgrid": False},
            "yaxis": {"fixedrange": True, "showgrid": False},
        }
    )
```
did not seem to affect the subplots.

---

# New layout

image

# Bonus
I added [Font Awesome](https://fontawesome.com/icons) stylesheet to our app so feel free to add any of their icons whenever suitable.

### CODE REVIEW

**Comment by zuzg** [comment]
Have you tried `layout.xaxis.rangeslider.visible = false` or `modebar_remove=['zoom', 'pan']`?

**Review by zuzg — COMMENTED** [review]
Nice job, it looks more intuitive now! Could you also remove gridlines? It is just `showgrid=False` in the axes dict

**Review by AndrzejKaj — APPROVED** [review]
It looks very good

**Comment by Tremirre** [comment]
Thanks @zuzg! didn't know you have to add axis index in the layout dict
Zooming and panning on heatmaps is now disabled

**Review by zuzg — APPROVED** [review]
🤩🥳😻

**Review by azywot — APPROVED** [review]
LGTM!

**Pull request merged**
