### PR TITLE
closes 182 screening process adjustments

### PR DESCRIPTION
**Pull request by Tremirre**
Fixed bug that prevented client's bmg file from being uploaded (it had an empty newline).

To prevent any further issues, I added simple error handling - bad files will not be parsed and will be reported to the user alongside the message why they failed (example: failing data from confirmatory screening)
image

Added new button that allows to download all heatmaps as a single file:
image

### CODE REVIEW

**Comment by Tremirre** [comment]
example heatmap exports (one with 24 assays and one with 253 assays)
[heatmaps.zip](https://github.com/zuzg/drug-screening/files/13504682/heatmaps.zip)

**Review by AndrzejKaj — APPROVED** [review]
Tested locally. Works very good. 📈

**Review by azywot — APPROVED** [review]
Tested locally, LGTM 👍👍🫡🫡
_One minor suggestion: maybe we could move the export button somewhere here?_
obraz

**Review by zuzg — APPROVED** [review]
Nice! One thing, I would reduce the amount of white padding between the exported heatmaps (only if it's low-effort update 😉)

**Comment by Tremirre** [comment]
branch broke

**Pull request closed without merging**
